### ISSUE TITLE
Define MVP (Minimum Viable Product) for V1

### ISSUE THREAD

**Issue by voxelv** [GodlyGames/GIGWorlds#1]
"The world has yet to see what can be accomplished with unrestricted scope creep"

In order to achieve the goals of this project, we must define those goals.

I recommend we define these goals in a shared space (such as the repository's wiki).

**Comment by EveryGoodWork** [comment]
As this won't be a "For Sale" product and instead an ongoing development which will be part of the defining aspects of this endeavor, creep for us is good, if it is driven by the user base and meets the objectives set by GIGWorlds visions.  The Rapid Application Development (RAD) and rolling forward model with continuous releases will make the process of making the game/worlds, part of the game.

**Comment by EveryGoodWork** [comment]
Character movement, multiplayer, Audio area chat, and basic game mechanics achieved.  Deployed to online servers and had a great time with V1.8.1 of Tag on 3/12.  This was lives streamed on http://twitch.tv/MissionaryGamer and with highlights uploaded to http://YouTube.com/MissionaryGamer.
